apiVersion: v1
kind: Pod
metadata:
  annotations:
    cattle.io/timestamp: "2020-06-05T08:12:08Z"
    cni.projectcalico.org/podIP: 10.42.0.10/32
    cni.projectcalico.org/podIPs: 10.42.0.10/32
    field.cattle.io/ports: '[[{"containerPort":53,"dnsName":"pihole-hostport","hostPort":53,"kind":"HostPort","name":"dns-tcp","protocol":"TCP","sourcePort":53},{"containerPort":53,"dnsName":"pihole-hostport","hostPort":53,"kind":"HostPort","name":"dns-udp","protocol":"UDP","sourcePort":53},{"containerPort":80,"dnsName":"pihole-hostport","hostPort":8001,"kind":"HostPort","name":"pihole-http","protocol":"TCP","sourcePort":8001}]]'
  creationTimestamp: "2020-06-05T08:12:19Z"
  generateName: pihole-5f9fd96596-
  labels:
    pod-template-hash: 5f9fd96596
    workload.user.cattle.io/workloadselector: deployment-default-pihole
  name: pihole-5f9fd96596-lpgcp
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: pihole-5f9fd96596
    uid: 02187398-0eb3-4a8b-bf4f-183a678aa7ac
  resourceVersion: "77551"
  selfLink: /api/v1/namespaces/default/pods/pihole-5f9fd96596-lpgcp
  uid: dde70835-6251-451b-9115-a3da6651cc7d
spec:
  containers:
  - env:
    - name: DNS1
      value: 9.9.9.9
    - name: DNS2
      value: 1.1.1.1
    - name: ServerIP
      value: 10.1.1.148
    - name: TZ
      value: Asia/Singapore
    image: pihole/pihole:latest
    imagePullPolicy: Always
    name: pihole
    ports:
    - containerPort: 53
      hostPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 53
      hostPort: 53
      name: dns-udp
      protocol: UDP
    - containerPort: 80
      hostPort: 8001
      name: pihole-http
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      runAsNonRoot: false
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /etc/pihole/
      name: pihole-etc
    - mountPath: /etc/dnsmasq.d/
      name: pihole-dnsmasq
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-g8p5n
      readOnly: true
  dnsConfig:
    nameservers:
    - 127.0.0.1
    - 9.9.9.9
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - hostPath:
      path: /Users/garrygoh/Downloads/pihole/etc-pihole/
      type: ""
    name: pihole-etc
  - hostPath:
      path: /Users/garrygoh/Downloads/pihole/etc-dnsmasq.d/
      type: ""
    name: pihole-dnsmasq
  - name: default-token-g8p5n
    secret:
      defaultMode: 420
      secretName: default-token-g8p5n
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T08:12:19Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T08:12:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T08:12:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-06-05T08:12:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://7b51e204b55d909d728587c472af19c68f8b409809188f2ddf7e76891b468398
    image: pihole/pihole:latest
    imageID: docker-pullable://pihole/pihole@sha256:d586f1a05c2a81b224d2c30d33ab9081b8baa0471f87d900d55e6155ed89cb08
    lastState: {}
    name: pihole
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-06-05T08:12:26Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.42.0.10
  podIPs:
  - ip: 10.42.0.10
  qosClass: BestEffort
  startTime: "2020-06-05T08:12:19Z"

