version: "3.8"

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - SERVERURL=garrygoh.ddns.net
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=10.1.1.10
      - INTERNAL_SUBNET=10.13.13.0
    volumes:
      - /home/pi/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
